Web/Models/ClienteViewModel.cs
using Data.Entity;

namespace Web.Models
{
    public class ClienteViewModel
    {
        public  required List<EntityCliente>ListCliente {  get; set; }
    }
}

Web/Models/ErrorViewModel.cs
namespace Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Web/Models/ReservasViewModel.cs
using Data.Entity;

namespace Web.Models
{
    public class ReservasViewModel
    {
        public List<EntityReservas>? ListReservas { get; set; }
        public List<string>? ListaTipoVehiculos { get; set; }
        public List<EntityCliente>? ListCliente { get; set; }
        public List<EntityVehiculos>? ListaVehiculos { get; set; }
        public int ClienteId { get; set; }

        public int VehiculosId { get; set; }

        public DateTime FechaInicio { get; set; }
        public DateTime FechaFin {  get; set; }

    }
}

Web/Models/VehiculoViewModel.cs
using Data.Entity;

namespace Web.Models
{
    public class VehiculoViewModel
    {
        public string? Mensaje { get; set; }
        public required List<EntityVehiculos> ListVehiculos { get; set; }
    }
}

Web/Controllers/ClienteController.cs
using Bussiness.services;
using Data.Entity;
using Microsoft.AspNetCore.Mvc;
using Web.Models;

namespace Web.Controllers
{
    public class ClienteController : Controller
    {

        private readonly ILogger<ClienteController> _logger;
        private readonly ClienteService _clienteService;

        public ClienteController(ILogger<ClienteController> logger, ClienteService clienteService)
        {
            _clienteService = clienteService;
            _logger = logger;

        }

        public IActionResult Index()
        {
            _logger.LogInformation("inicia vista clientes");
            var vieModel = new ClienteViewModel
            {
                ListCliente = _clienteService.ObtenerClientes(),
            };
            return View(vieModel);
        }

        public IActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Crear(EntityCliente entityCliente)
        {
            if (ModelState.IsValid)
            {
                _clienteService.GuardarCliente(entityCliente);
                return RedirectToAction("Index");
            }
            return View(entityCliente);
        }


    }
}

Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Web.Models;

namespace Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Web/Controllers/ReservasController.cs
using Bussiness.services;
using Data.Entity;
using Microsoft.AspNetCore.Mvc;
using Web.Models;

namespace Web.Controllers
{
    public class ReservasController  : Controller
    {

        private readonly ILogger<ReservasController> _logger;
        private readonly ReservasService _reservasService;
        private readonly VehiculoService _vehiculoService;
        private readonly ClienteService _clienteService;
        
        public ReservasController(ILogger<ReservasController> logger, ReservasService reservasService, VehiculoService vehiculoService, ClienteService clienteService )
        {
            _clienteService = clienteService;
            _vehiculoService = vehiculoService;
            _reservasService = reservasService;
            _logger = logger;
        }

        public IActionResult Index() 
        {
            _logger.LogInformation("Inicia vista de Reservas");
            

            var viewModel = new ReservasViewModel
            {
                ListReservas = _reservasService.ObtenerReservas()
            };
            return View(viewModel);
        }

       
        public IActionResult Crear()
        {
            var viModel = new ReservasViewModel
            {
                ListCliente = _clienteService.ObtenerClientes(),
                ListReservas = _reservasService.ObtenerReservas(),
                ListaTipoVehiculos = _vehiculoService.GetTiposVehiculos(),
                ListaVehiculos = _vehiculoService.ObtenerVehiculos()
            };
            return View(viModel);
        }

        [HttpPost]
        public IActionResult CrearReserva(ReservasViewModel viewModel)
        {
            var reserva = new EntityReservas();

            var cliente = _clienteService.GetClienteId(viewModel.ClienteId);
            var vehiculo = _vehiculoService.GetVehiculoId(viewModel.VehiculosId);

            if (ModelState.IsValid){

                reserva.Cliente = cliente;
                reserva.Vehiculo = vehiculo;
                reserva.FechaInicio = viewModel.FechaInicio;
                reserva.FechaFin = viewModel.FechaFin;

                _reservasService.GuardarReservas(reserva);
                return RedirectToAction("Index");
            }
            return View(reserva);

        }

        public IActionResult Pago(EntityReservas entityReservas) 
        {
            return View(entityReservas);
        }
    }
}

Web/Controllers/VehiculoController.cs
using Bussiness.services;
using Microsoft.AspNetCore.Mvc;
using Web.Models;


namespace Web.Controllers
{
    public class VehiculoController : Controller
    {
        private readonly ILogger<VehiculoController> _logger;
        private readonly VehiculoService _vehiculoService;

        public VehiculoController(ILogger<VehiculoController> logger, VehiculoService vehiculoService)
        {
            _vehiculoService = vehiculoService;
            _logger = logger;
        }

        public IActionResult Index()
        {

            _logger.LogInformation("Inicia vista");

            var viewModel = new VehiculoViewModel
            {
                Mensaje = _vehiculoService.MensajePrueba(),
                ListVehiculos = _vehiculoService.ObtenerVehiculos(),
            };

            return View(viewModel);
        }

        public IActionResult Crear()
        {
            return View();
        }


    }
}

Web/Views/Cliente/Crear.cshtml
@model Data.Entity.EntityCliente
@{
    ViewData["Title"] = "Crear";
}

<h1>Crear Cliente</h1>

<div>
    <form class="container-fluid" asp-controller="Cliente" asp-action="Crear" method="post">
        <div class="container-fluid">
            <div class="row py-3">
                <div class="mb-3 col-4">
                    <label asp-for="Documento" class="form-label">Documento</label>
                    <input asp-for="Documento" class="form-control" />
                    <span asp-validation-for="Documento" class="text-danger"></span>
                </div>
                <div class="mb-3 col-4">
                    <label asp-for="Nombre" class="form-label">Nombre</label>
                    <input asp-for="Nombre" class="form-control" />
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>
                <div class="mb-3 col-4">
                    <label asp-for="Email" class="form-label">Email</label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="mb-3 col-4">
                    <label asp-for="Telefono" class="form-label">Teléfono</label>
                    <input asp-for="Telefono" class="form-control" />
                    <span asp-validation-for="Telefono" class="text-danger"></span>
                </div>
                <div class="mb-3 col-4">
                    <label asp-for="Ciudad" class="form-label">Ciudad</label>
                    <input asp-for="Ciudad" class="form-control" />
                    <span asp-validation-for="Ciudad" class="text-danger"></span>
                </div>
                <div class="mb-3 col-4">
                    <label asp-for="Direccion" class="form-label">Dirección</label>
                    <input asp-for="Direccion" class="form-control" />
                    <span asp-validation-for="Direccion" class="text-danger"></span>
                </div>
                <div class="mb-3 col-4">
                    <label asp-for="Fecha_Nacimiento" class="form-label">Fecha de Nacimiento</label>
                    <input asp-for="Fecha_Nacimiento" class="form-control" />
                    <span asp-validation-for="Fecha_Nacimiento" class="text-danger"></span>
                </div>
            </div>
        </div>


        <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-success me-3">Save</button>
            <button asp-controller="Cliente" asp-action="Index" class="btn btn-danger">Cancelar</button>
        </div>
    </form>
</div>

Web/Views/Cliente/Index.cshtml
@model ClienteViewModel
@{
    ViewData["Title"] = "Index";
}
<div>
    <h1 class="my-2">Clientes</h1>

    <div class="my-2 d-flex justify-content-end">
        <a class="btn btn-success" asp-area="" asp-controller="Cliente" asp-action="Crear">Crear Cliente</a>
    </div>

    <div class="my-4">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Documento</th>
                    <th scope="col">Ciudad</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Email</th>
                    <th scope="col">Telefono</th>
                    <th scope="col">Direccion</th>
                    <th scope="col">Fecha Nacimiento</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var cliente in Model.ListCliente)
                {
                    <tr>
                        <td>@cliente.Id</td>
                        <td>@cliente.Documento</td>
                        <td>@cliente.Ciudad</td>
                        <td>@cliente.Nombre</td>
                        <td>@cliente.Email</td>
                        <td>@cliente.Telefono</td>
                        <td>@cliente.Direccion</td>
                        <td>@cliente.Fecha_Nacimiento</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    

</div>




   

Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <button type="button" class="btn btn-primary">Primary</button>
</div>

Web/Views/Reservas/Crear.cshtml
@model ReservasViewModel 

@{
    ViewData["Title"] = "Crear";
    var hoy = DateTime.Now.ToString("yyyy-MM-dd");
}

<h1>Crear Reserva</h1>
    <div class="d-flex justify-content-center">
        <div class="p-3 d-flex justify-content-start">
            <p>Solicitud #1</p>
        </div>
        <div class="p-3  d-flex justify-content-end">
            <p>Fecha Actualizacion:01/01/2024</p>
        </div>
    </div>

<div>
    <form class="container-fluid" asp-controller="Reservas" asp-action="CrearReserva" method="post">
        <div class="container-fluid">
            <div class="row py-3">
                <div class="mb-3 col-4">
                    <label for="basic-url" asp-for="ClienteId" class="form-label">Cliente</label>
                    <select class="form-select" aria-label="Default select example" asp-for="ClienteId">
                        <option selected>Select...</option>
                        @foreach (var cliente in Model.ListCliente)
                        {
                            <option value="@cliente.Id">@cliente.Nombre</option>
                        }
                    </select>
                </div>
                <div class="mt-2 pt-4 col-4">
                    <a  class="btn btn-success me-3" asp-controller="Cliente" asp-action="Crear">Crear Cliente</a>
                </div>
                @*
                <div class="mb-3 col-5">
                <label for="basic-url" class="form-label">Tipo de vehiculo</label>
                <select class="form-select" aria-label="Default select example">
                <option selected>Select...</option>
                @foreach (var tipoVehiculo in Model.ListaTipoVehiculos)
                {
                <option value="@tipoVehiculo">@tipoVehiculo</option>
                }
                </select>
                </div>
                *@
               
                <div class="mb-3 col-5">
                    <label for="basic-url" asp-for="VehiculosId" class="form-label">vehiculos</label>
                    <select class="form-select" aria-label="Default select example" asp-for="VehiculosId">
                        <option selected>Select...</option>
                        @foreach (var vehiculo in Model.ListaVehiculos)
                        {
                            <option value="@vehiculo.Id">@vehiculo.Placa</option>
                        }
                    </select>
                </div>
                <div class="mb-3 col-4">
                    <label asp-for="FechaInicio" class="form-label">Fecha Inicio</label>
                    <input asp-for="FechaInicio" type="date" class="form-control" min="@hoy" value="@hoy" />
                </div>
                <div class="mb-3 col-4">
                    <label asp-for="FechaFin" class="form-label">Fecha Fin</label>
                    <input asp-for="FechaFin" type="date" class="form-control" min="@hoy" />
                </div>
            </div>
        </div>
        <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-success me-3" asp-controller="Reservas" asp-action="CrearReserva">Pagar</button>
            <button asp-controller="Reservas" asp-action="Index" class="btn btn-danger">Cancelar</button>
        </div>
    </form>
</div>

Web/Views/Reservas/Index.cshtml
@model ReservasViewModel
@{
    ViewData["Title"] = "Index";
}

<h1>Reservas</h1>

<p><a class="btn btn-success" asp-controller="Reservas" asp-action="Crear">Crear Reserva</a></p>

<table class="table">
    <thead>
        <tr>
            <th>#</th>
            <th>Estado</th>
            <th>Vehículo</th>
            <th>Cliente</th>
            <th>Fecha Inicio</th>
            <th>Fecha Fin</th>
            <th>Tipo Pago</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var reserva in Model.ListReservas)
        {
            <tr>
                <td>@reserva.IdReserva</td>
                <td>@(reserva.Estado != null ? reserva.Estado.Tipo : "N/A")</td>
                <td>@(reserva.Vehiculo != null ? reserva.Vehiculo.Placa : "N/A")</td>
                <td>@(reserva.Cliente != null ? reserva.Cliente.Nombre : "N/A")</td>
                <td>@reserva.FechaInicio.ToString("yyyy-MM-dd")</td>
                <td>@reserva.FechaFin.ToString("yyyy-MM-dd")</td>
                <td>@(reserva.TipoPago != null ? reserva.TipoPago.Tipo : "N/A")</td>
            </tr>
        }
    </tbody>
</table>

Web/Views/Reservas/Pago.cshtml
@{
    ViewData["Title"] = "Pago";
}

<h1>Realizar pago</h1>
<div>
    <form class="container-fluid" asp-controller="Reservas" asp-action="Pago"  method="post">
        <div class="container-fluid">
           <div class="row py-3">
                <div class="col-auto">
                    <label for="inputPassword2" class="visually-hidden">Dias</label>
                    <input type="number" class="form-control" id="inputDias" placeholder="Dias">
                </div>
                <div class="col-auto">
                    <label for="costodias" class="visually-hidden">Costo Dias</label>
                    <input type="number" class="form-control" id="inputCostoDias" placeholder="Costo de Dias">
                </div>
                <div class="col-auto">
                    <label for="impuesto" class="visually-hidden">Impuesto</label>
                    <input type="number" class="form-control" id="inputCostoDias" placeholder="impuesto">
                </div>
                <div>
                    <label for="basic-url" class="form-label">Tipo Pago</label>
                    <select class="form-select" aria-label="Default select example">
                        <option selected>Open this select menu</option>
                        <option value="1">Tarjeta de Credito</option>
                        <option value="2">Transferencia ancaria</option>
                        <option value="3">Destino</option>
                    </select>
                </div>
           </div>
        </div>

        <div>
            <button type="submit" class="btn btn-success me-3 asp-controller="Reservas" asp-action="Crear">Volver</button>
            <button asp-controller="Reservas" asp-action="Index" class="btn btn-danger">Pagar</button>
        </div>
    </form>
</div>

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Miles Car Rental</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reservas" asp-action="Index">Reservas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Clientes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            Alix Meneses &copy; 2024 - Web - <a asp-area="" asp-controller="Home" asp-action="Privacy"></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Web/Views/Vehiculo/Crear.cshtml
@{
    ViewData["Title"] = "Crear";
}

<h1>Crear</h1>

Web/Views/Vehiculo/Index.cshtml
@model VehiculoViewModel
@{
    ViewData["Title"] = "Index";
}

<h1>@Model.Mensaje</h1>

@foreach (var vehiculo in Model.ListVehiculos)
{
    <tr></tr>
    <h2>@vehiculo.Placa</h2>
}